sudo: false
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"

git:
  autocrlf: input

os:
  - linux
  - windows
  - osx

before_install:  
  - travis_retry npx npm@7 install
  
install:
  - npm --version

script:
  - npx npm@7 test
  
matrix:
  exclude:
    - os: windows
      node_js: "8"
